---
- name: Reboot server
  reboot:
   reboot_timeout: 3600

#- name: Wait for the server to finish rebooting
#  local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300 delay=30
